TP1/TP1-CreditImmobilier/Controllers/SimulationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TP1_CreditImmobilier.Models;

namespace TP1_CreditImmobilier.Controllers
{
    public class SimulationController : Controller
    {

        private void majResultatSimulation(ResultatSimulationModel resultatSimulation) 
        {
            for (int ech = 0; ech < resultatSimulation.simulation.dureePret; ech++) 
            {
                LigneTableauAmortissementModel la = new LigneTableauAmortissementModel();
                if (ech == 0)
                {
                    la.capitalRestant = resultatSimulation.simulation.capitalEmprunte;
                }
                else
                {
                    LigneTableauAmortissementModel laPrec = resultatSimulation.listeLignesAmortissement[ech - 1];
                    la.capitalRestant = Math.Round(laPrec.capitalRestant - laPrec.amortissement, SimulationModel.nbDecimal);
                }
                la.interet = Math.Round(la.capitalRestant * resultatSimulation.simulation.tauxInteretPeriodique, SimulationModel.nbDecimal);
                resultatSimulation.coutTotalInteret += la.interet;
                if (ech < resultatSimulation.simulation.dureePret - 1)
                {
                    la.amortissement = Math.Round(resultatSimulation.simulation.montantEcheances - la.interet, SimulationModel.nbDecimal);
                }
                else
                {
                    la.amortissement = la.capitalRestant;
                }
                la.frais = Math.Round(resultatSimulation.simulation.montantEcheancesAssurance, SimulationModel.nbDecimal);
                resultatSimulation.coutTotalAssurance += la.frais;
                la.montantReel = la.interet + la.amortissement + la.frais;
                resultatSimulation.coutTotalPret += la.montantReel;
                resultatSimulation.listeLignesAmortissement.Add(la);
            }
        }
        //
        // GET: /Simulation/

        public ActionResult Index()
        {
            return View();
        }
        
        [HttpGet]
        public ActionResult Create()
        {
            SimulationModel s = new SimulationModel();
            s.nomClient = "Pierre de Perpignan";
            s.date = DateTime.Now;
            ViewBag.simulation = s;
            return View(s);
        }

        [HttpPost]
        public ActionResult Create(SimulationModel s)
        {
            if (ModelState.IsValid)
            {
                ResultatSimulationModel simulationResult = new ResultatSimulationModel();
                simulationResult.simulation = s;
                majResultatSimulation(simulationResult);
                return View("~/Views/Shared/Resultat.cshtml", simulationResult);
            }
            else
            {
                return View(s);
            }
        }
    }
}

TP1/TP1-CreditImmobilier/Views/Shared/Create.cshtml
@model TP1_CreditImmobilier.Models.SimulationModel
@{
    ViewBag.Title = "Create";
}


<h2>Create</h2>

<h2>Bienvenue @Model.nomClient</h2>
<p>Vous avez réalisé une simulation le @Model.date</p>
@Html.BeginForm("Create", "Simulation")

@Html.LabelFor(s => s.capitalEmprunte)
@Html.TextBoxFor(s => s.capitalEmprunte)
@Html.ValidationMessageFor(s => s.capitalEmprunte)

@Html.LabelFor(s => s.dureePret)
@Html.TextBoxFor(s => s.dureePret)
@Html.ValidationMessageFor(s => s.dureePret)

@Html.LabelFor(s => s.nbEcheanceParAn)
@Html.DropDownListFor(s => s.nbEcheanceParAn, Model.getNombreEcheance)
@Html.ValidationMessageFor(s => s.nbEcheanceParAn)

@Html.LabelFor(s => s.montantEcheances)
<span id="montantEcheance">0</span>
@Html.ValidationMessageFor(s => s.montantEcheances)

@Html.LabelFor(s => s.tauxInteretAnnuel)
@Html.TextBoxFor(s => s.tauxInteretAnnuel)   
@Html.ValidationMessageFor(s => s.tauxInteretAnnuel)

@Html.LabelFor(s => s.tauxAssurance)
@Html.TextBoxFor(s => s.tauxAssurance)
@Html.ValidationMessageFor(s => s.tauxAssurance)

@Html.LabelFor(s => s.tauxPeriodiqueAssurance)
<span id="tauxPeriodiqueAssurance">1</span>

@Html.LabelFor(s => s.tauxInteretPeriodique)
<span id="tauxInteretPeriodique">120</span>

@Html.LabelFor(s => s.montantEcheancesAssurance)
<span id="montantEcheanceAssurance">3</span>
<input type="submit" value="Valider"/>

@{Html.EndForm();}

TP1/TP1-CreditImmobilier/Views/Shared/Resultat.cshtml
@{
    ViewBag.Title = "Resultat";
}

<h2>Resultat</h2>
<p>tu veux voir ma bite ?</p>

TP1/TP1-CreditImmobilier/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">
    <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Mon application ASP.NET MVC</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/simulation_script")


    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("votre logo ici", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                            <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Simulation","Create","Simulation")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Mon application ASP.NET MVC</p>
                </div>
            </div>
        </footer>
           


    </body>
</html>